update actions

diff --git a/.github/actions/terraform-plan/action.yml b/.github/actions/terraform-plan/action.yml
--- a/.github/actions/terraform-plan/action.yml
+++ b/.github/actions/terraform-plan/action.yml
@@ -32,56 +32,21 @@ runs:
         terraform plan -no-color -out=${{ inputs.terraform-plan-output }} > /dev/null
         terraform show -no-color ${{ inputs.terraform-plan-output }}
       shell: bash
+      continue-on-error: true
     - name: Display Terraform plan on summary
-      working-directory: ${{ inputs.terraform-directory }}
+      if: steps.tfplan.outputs.exitcode == 0
       run: |
         echo "### Terraform Plan on ${{ inputs.envname }} from $GITHUB_REF_NAME :rocket:" >> $GITHUB_STEP_SUMMARY
         echo '~~~' >> $GITHUB_STEP_SUMMARY
         echo "${{ steps.tfplan.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY
         echo '~~~' >> $GITHUB_STEP_SUMMARY
       shell: bash
-    - name: Terraform PR
-      uses: actions/github-script@v6
-      if: github.event_name == 'pull_request'
-      with:
-        github-token: ${{ inputs.github-token }}
-        script: |
-          // 1. Retrieve existing bot comments for the PR
-          const { data: comments } = await github.rest.issues.listComments({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            issue_number: context.issue.number,
-          })
-          const botComment = comments.find(comment => {
-            return comment.user.type === 'Bot' && comment.body.includes('Terraform Plan')
-          })
-
-          // 2. Prepare format of the comment
-          const output = `#### Terraform Plan 📖\`${{ steps.tfplan.outcome }}\`
-
-          <details><summary>Show Plan</summary>
-
-          \`\`\`\n
-          ${{ steps.tfplan.outputs.stdout }}
-          \`\`\`
-
-          </details>
-
-          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
-
-          // 3. If we have a comment, update it, otherwise create a new one
-          if (botComment) {
-            github.rest.issues.updateComment({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              comment_id: botComment.id,
-              body: output
-            });
-          } else {
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            });
-          }
+    - name: Display Terraform Error on summary
+      if: steps.tfplan.outputs.exitcode != 0
+      run: |
+        echo "### Terraform ERROR on ${{ inputs.envname }} from $GITHUB_REF_NAME :rocket:" >> $GITHUB_STEP_SUMMARY
+        echo '~~~' >> $GITHUB_STEP_SUMMARY
+        echo "${{ steps.tfplan.outputs.stderr }}" >> $GITHUB_STEP_SUMMARY
+        echo '~~~' >> $GITHUB_STEP_SUMMARY
+        exit ${{ steps.tfplan.outputs.exitcode }}
+      shell: bash
