Revert "gha matrix example"
This reverts commit e0a238f97d8ea3219a678ea75cd123096c4a4813.

diff --git a/.github/workflows/gha-matrix.yml b/.github/workflows/gha-matrix.yml
--- a/.github/workflows/gha-matrix.yml
+++ b/.github/workflows/gha-matrix.yml
@@ -16,7 +16,8 @@ jobs:
         name: Step One
         run: |
           if [[ "${{ matrix.type_a }}" == "type_a_01" ]]; then
-            core.setFailed("FAIL Step One: key:${{ matrix.type_a }}")
+            echo "FAIL Step One: key:${{ matrix.type_a }}" >> $GITHUB_STEP_SUMMARY
+            exit 1
           else
             echo "Step One: key:${{ matrix.type_a }}" >> $GITHUB_STEP_SUMMARY
           fi
@@ -40,7 +41,8 @@ jobs:
         name: Step One
         run: |
           if [[ "${{ matrix.type_b }}" == "type_b_01" ]]; then
-            core.setFailed("FAIL Step One: key:${{ matrix.type_b }}")
+            echo "FAIL Step One: key:${{ matrix.type_b }}" >> $GITHUB_STEP_SUMMARY
+            exit 1
           else
             echo "Step One: key:${{ matrix.type_b }}" >> $GITHUB_STEP_SUMMARY
           fi
@@ -64,7 +66,8 @@ jobs:
         name: Step One
         run: |
           if [[ "${{ matrix.type_c }}" == "type_c_01" ]]; then
-            core.setFailed("FAIL Step One: key:${{ matrix.type_c }}")
+            echo "FAIL Step One: key:${{ matrix.type_c }}" >> $GITHUB_STEP_SUMMARY
+            exit 1
           else
             echo "Step One: key:${{ matrix.type_c }}" >> $GITHUB_STEP_SUMMARY
           fi
