gha matrix example

diff --git a/.github/workflows/gha-matrix.yml b/.github/workflows/gha-matrix.yml
--- a/.github/workflows/gha-matrix.yml
+++ b/.github/workflows/gha-matrix.yml
@@ -3,10 +3,36 @@ on:
   workflow_dispatch:
 
 jobs:
-  test_matrix_b:
+  fft_coet:
     runs-on: ubuntu-latest
+    continue-on-error: true
     strategy:
-      # fail-fast: true
+      fail-fast: true
+      matrix:
+        type_a: [type_a_00, type_a_01, type_a_02]
+
+    steps:
+      -
+        name: Step One
+        run: |
+          if [[ "${{ matrix.type_a }}" == "type_a_01" ]]; then
+            echo "FAIL Step One: key:${{ matrix.type_a }}" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo "Step One: key:${{ matrix.type_a }}" >> $GITHUB_STEP_SUMMARY
+          fi
+
+      -
+        name: Step Two
+        run: |
+          sleep 60
+          echo "Step Two: key:${{ matrix.type_a }}" >> $GITHUB_STEP_SUMMARY
+
+  all_fail:
+    runs-on: ubuntu-latest
+    continue-on-error: false
+    strategy:
+      fail-fast: true
       matrix:
         type_b: [type_b_00, type_b_01, type_b_02]
 
